### ISSUE TITLE
Failed to load some NODES

### ISSUE THREAD

**Issue by Abdulix** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#12]
Install the node in Comfyui/custom_nodes and install all the requirements through comfyui manager but showing import failed.  

![Screenshot from 2024-07-03 17-59-37](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/assets/106888411/c9cbff5a-a698-4aa5-9b8b-67e08f6c5276)

**Comment by cdb-boop** [comment]
My guess is that the nodes are failing to load because there are missing python packages. Installing requirements and troubleshooting installation are noted in the [Read Me](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/tree/master?tab=readme-ov-file#1-requirements).

However, if there are any error messages in the command line, if you could show me them then I might be able to narrow the issue down further.

**Comment by Abdulix** [comment]
The Python 3.10.14 , cmake version 3.29.6, dlib version 19.24.1 and wheel version 0.43.0 is already installed in my ubuntu conda environment.
But still it shows this error in my terminal :

Cannot import /media/../ComfyUI/custom_nodes/ComfyUI-Bringing-Old-Photos-Back-to-Life module for custom nodes: /home/../anaconda3/envs/cui/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/../anaconda3/envs/cui/lib/python3.10/site-packages/_dlib_pybind11.cpython-310-x86_64-linux-gnu.so)

my gcc version is : gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

**Comment by cdb-boop** [comment]
I don't have a linux machine set up atm, but I could get one running. However, before I do that, have you tried uninstalling your dlib and then reinstalling it? The issue appears to be with dlib and so I want to be sure that it was properly set up.

```
path\to\python.exe -m pip uninstall dlib
path\to\python.exe -m pip install dlib
```

**Comment by Abdulix** [comment]
still same error

**Comment by Abdulix** [comment]
**SOLVED!!**  

If anyone gets this type of error run this command in your conda environment :

` conda install -c conda-forge gcc`
