### ISSUE TITLE
It seems very memory-intensive

### ISSUE THREAD

**Issue by 0002kgHg** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#23]
I'm using an A100 graphics card with 40GB of VRAM, but running both 512x512 and 1024x1024 images leads to memory overload. Did I do something wrong?"
![workflow](https://github.com/user-attachments/assets/5e19a853-1c3b-4dc6-8a4c-05bca4ec516b)

**Comment by cdb-boop** [comment]
Your setup looks fine from what I can see.

I believe the VRAM usage depends mainly on the image size. Is your image very large? If so, you can use the built-in `Upscale Image By` or `Upscale Image` nodes to shrink the image.

It runs on my 12GB VRAM GPU locally. If you can provide more information, like the command line errors, errors in ComfyUI or workflow, I may be able to pinpoint what the problem is.
